"""
Signal dataclass for strategy outputs.
"""
from dataclasses import dataclass, asdict
from typing import Literal


@dataclass
class Signal:
    """
    Represents a trading signal generated by a strategy.
    
    Attributes:
        symbol: The stock ticker (e.g., 'PLTR')
        action: The recommended action - BUY, SELL, or HOLD
        confidence: Confidence level from 0.0 to 1.0
        strategy_name: Name of the strategy that generated this signal
        reason: Human-readable explanation for the signal
    """
    symbol: str
    action: Literal["BUY", "SELL", "HOLD"]
    confidence: float
    strategy_name: str
    reason: str
    
    def __post_init__(self):
        """Validate signal parameters."""
        if self.action not in ("BUY", "SELL", "HOLD"):
            raise ValueError(f"Invalid action: {self.action}. Must be BUY, SELL, or HOLD")
        
        # Clamp confidence to valid range
        self.confidence = max(0.0, min(1.0, self.confidence))
    
    def to_dict(self) -> dict:
        """Convert signal to dictionary for tool output."""
        return asdict(self)
    
    @classmethod
    def hold(cls, symbol: str, reason: str = "No clear signal") -> "Signal":
        """Create a HOLD signal with zero confidence."""
        return cls(
            symbol=symbol,
            action="HOLD",
            confidence=0.0,
            strategy_name="default",
            reason=reason
        )

